### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/Compass#12]
There are a few things required during setup that aren't explicitly noted in the readme. Some of them are Lumen framework things, others are just missing. @edwardhinkle just got everything running and was taking notes.

**Comment by aaronpk** [comment]
@veer0318 (from the Overland issue)

I've expanded the installation instructions based on notes from helping people set it up. https://github.com/aaronpk/Compass#setup

I'm guessing the issue you're running into is that either the database tables don't exist, or the data folder isn't writable. Can you run through the notes there and see if that solves it?

**Comment by veer0318** [comment]
Thanks, I fixed it. The only thing was that I didn't have a slash at the end of my data dir path in .env. Fixed that, now it works.


Great app btw, you literally - and in all features - made the app I was thinking for quite some time of making. You did a better job than I could, though. ;)

A bit off-topic: I have a lot of data from an earlier app I used, that's in KML format (can transfer to any format). Would you happen to know of any tool that can easily convert my old data to the new format? Otherwise I'll write something myself.

**Comment by aaronpk** [comment]
Awesome, thanks! This storage format isn't something standard, so I doubt you'd find an existing tool to do the job. I'd recommend writing the old data the same way Compass does, using the QuartzDB library. Check out [API.php line 223](https://github.com/aaronpk/Compass/blob/master/compass/app/Http/Controllers/Api.php#L223) to see how Compass does it. Basically:

```php
$qz = new Quartz\DB(env('STORAGE_DIR').$db->name, 'w');

// for each point, build the GeoJSON record as $loc then run:
  $date = new DateTime($loc['properties']['timestamp']);
  $qz->add($date, $loc);
```

The QuartzDB library will handle creating the nested folder structure and ensure it's written in the format Compass expects.
